name: arabic_manga_readers
description: Manga For Arabs.

publish_to: "none"

version: 1.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.8.0
  cloud_firestore: ^2.5.4
  get: ^4.3.8
  photo_view: ^0.13.0
  flutter_rating_stars: ^1.0.3+4
  shimmer: ^2.0.0
  cached_network_image: ^3.1.0+1
  google_fonts: ^2.1.0
  hive_flutter: ^1.1.0
  hive: ^2.0.4
  flutter_screenutil: ^5.0.0+2
  google_mobile_ads: ^0.13.6
  path_provider: ^2.0.6
  permission_handler: ^8.2.6
  image_downloader: ^0.30.0
  pdf: ^3.6.2
  firebase_messaging: ^11.1.0
  rate_my_app: ^1.1.1
  flutter_local_notifications: ^9.1.4
  rxdart: ^0.27.2
  facebook_audience_network: ^1.0.0-nullsafety.0
  facebook_app_events: ^0.14.7

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: "assets/app_logo.png"
  image_path_android: "assets/app_logo.png"
  android: true

  
  hive_generator: ^1.1.1
  build_runner: ^2.1.5

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
 
